# DSC4828 Assignment 2

**Due date: Monday 17/05/2024 21h00** <br>
**Total marks: 60** <br> 

**Your name:** Mynhardt L. Traut     <br>
**Your student number:** 54763088        <br>
**Your email address:** mynhardt.traut@gmail.com         <br>

**Instructions:** 
1. Complete the tasks below by editing/adding the code in the code cells directly below each question. 
2. Submit your completed .ipynb file on the module website under the appropriate link.

For any queries about this assignment, email Katherine Malan at malankm@unisa.ac.za

## Question 1: debugging  (9 marks)
The following code is supposed to print out the Fibonacci sequence up to the number of terms specified by the user.
For example, if the user enters 10, the output should be:

Fibonacci sequence of 10  terms:<br>
0, 1, 1, 2, 3, 5, 8, 13, 21, 34

However, the program contains a number of errors. Your task is to fix the code until it works correctly.<br>
For each error that you find in the program, add a comment to explain the error.

In [1]:
num_terms = int(input("Enter the number of terms: "))  # Convert input to integer
t1 = 0
t2 = 1
counter = 0  # Initialize counter for checking when to stop

if num_terms <= 0:
    print("No terms - number is not positive")
else:
    print("Fibonacci sequence of", num_terms, "terms:")
    while counter < num_terms:
        if counter == num_terms - 1:  # Check for last term
            print(t1)  # Print the last term without a comma
        else:
            print(t1, end=", ")
        
        # Compute the next term
        next_term = t1 + t2
        t1 = t2
        t2 = next_term
        counter += 1  # Increment the counter

Enter the number of terms: 20
Fibonacci sequence of 20 terms:
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181


## Question 2: number of characters and words (5 marks)
Write code to input a sentence from the user and output the number of characters in the sentence as well as the estimated number of words in the sentence (excluding leading or trailing spaces). **Hint**: You can estimate the number of words by counting the number of spaces in the sentence. 


In [47]:
# Input the sentence from the user
sentence = input("Please enter a sentence: ")

# Strip leading and trailing spaces to clean up the input
trim_sentence = sentence.strip()

# Count the characters in the cleaned-up sentence
num_chars = len(trim_sentence)

# Estimate the number of words. Check if the sentence is not empty to avoid incorrect counts
if trim_sentence:
    num_words = trim_sentence.count(" ") + 1  # Add one because words are one more than spaces
else:
    num_words = 0  # If the sentence is empty after stripping, set word count to zero

# Output the results
print("Number of characters:", num_chars)
print("Estimated number of words:", num_words)

Please enter a sentence:         this is my sentence       
Number of characters: 19
Estimated number of words: 4


## Question 3: Ackley's function (8 marks)
Write code to input two numbers from the user (x1 and x2) and then print out the result of the following fuction (known as Ackley's function). You can test your code using the following test cases: f(0,0) $\approx$ 0, and f(31.5, 31.5) $\approx$ 22.314. **Hint**: In Python, trigonometric functions (such as cos and sin) are defined in the math package. 

   $f(x_1,x_2) =   -20\,\textrm{exp}\big(-0.2\sqrt{0.5(x_1^2 + x_2^2)}\big)-\textrm{exp}(0.5(\cos2\pi x_1 + \cos2\pi x_2)) + 20 + \textrm{exp}(1)$

In [3]:
import math

# Ackley's function definition
def ackley(x1, x2):
    part1 = math.exp(-0.2 * math.sqrt(0.5 * (x1**2 + x2**2)))
    part2 = math.exp(0.5 * (math.cos(2 * math.pi * x1) + math.cos(2 * math.pi * x2)))
    return -20 * part1 - part2 + 20 + math.exp(1)

# Input from user
x1 = float(input("Enter x1: "))
x2 = float(input("Enter x2: "))

# Calculate and print the result
result = ackley(x1, x2)
print("Ackley's function value for (x1, x2) is:", result)

Enter x1: 31.5
Enter x2: 31.5
Ackley's function value for (x1, x2) is: 22.313676291747026


## Question 4: prime number (8 marks)
Write code to ask the user to enter an integer. Print a statement indicating whether the integer is a prime number or not.

In [49]:
# Function to check if input is prime
def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True  # 2 is a prime number
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Validate input from user to check if integer
while True:
    user_input = input("Enter an integer (or press enter to exit): ")
    if user_input.strip() == "":
        print("No input provided. Exiting.")
        break
    try:
        n = float(user_input)
        if n.is_integer():
            n = int(n)
            break
        else:
            print("You did not enter an integer. Please try again.")
    except ValueError:
        print("Invalid input. Please enter a valid integer.")

# Check if the number is prime and print the result
if user_input.strip() != "":
    if is_prime(n):
        print(f"The integer {n} is a prime number.")
    else:
        print(f"The integer {n} is not a prime number.")

Enter an integer (or press enter to exit): 1.5
You did not enter an integer. Please try again.
Enter an integer (or press enter to exit): 23
The integer 23 is a prime number.


## Question 5: round_list function (8 marks)
Write a function called round_list that takes two arguments: a list of real numbers and an integer. The function should create a new list containing the same number of real numbers as the original list, but rounded off to the number of decimals indicated by the second argument. For example, round_list( [12.34529, 10.6758, 11.6111, 56.89], 2) should return the list [12.35, 10.68, 11.61, 56.89]. <br>
Add code to test your function.

In [21]:
# Function to round the input numbers to specified decimals
def round_list(numbers, decimals):
    rounded_list = [round(float(num), decimals) for num in numbers]
    return rounded_list

# Function to prompt user to enter a list of numbers, exit upon empty input
def get_user_input():
    numbers = []
    print("Enter numbers one at a time. Press enter without typing a number to finish.")
    while True:
        user_input = input("Enter a number: ")
        if user_input.strip() == "":
            break
        try:
            # Convert to float to ensure the input can be rounded later
            num = float(user_input)
            numbers.append(num)
        except ValueError:
            print("Invalid input, please enter a valid number.")
    return numbers

# Get user inputs
user_numbers = get_user_input()
if user_numbers:
    while True:
        try:
            decimals = int(input("Enter the number of decimal places to round to: "))
            if decimals < 0:
                print("Please enter a non-negative integer for decimal places.")
            else:
                break
        except ValueError:
            print("Please enter an integer.")
    # Round the list and print the result
    result = round_list(user_numbers, decimals)
    print("Rounded numbers:", result)
else:
    print("No numbers were entered.")

Enter numbers one at a time. Press enter without typing a number to finish.
Enter a number: 0.9
Enter a number: 0.98
Enter a number: 0.987
Enter a number: 0.9876
Enter a number: 0.98765
Enter a number: 0.5
Enter a number: 0.54
Enter a number: 0.543
Enter a number: 0.5432
Enter a number: 0.54321
Enter a number: 0.55555
Enter a number: 0.56
Enter a number: 0.567
Enter a number: 0.5678
Enter a number: 0.56789
Enter a number: 
Enter the number of decimal places to round to: 3
Rounded numbers: [0.9, 0.98, 0.987, 0.988, 0.988, 0.5, 0.54, 0.543, 0.543, 0.543, 0.556, 0.56, 0.567, 0.568, 0.568]


## Question 6: first_duplicate function (8 marks)
Write a function called first_duplicate that takes a list as an argument and returns the first element that is duplicated in the list. If no duplicates are found, the function should return None. Hint: One way of doing this is to use the count method to see how many instances of each element there are. If there is more than 1, it means that that element is duplicated.

Write code to test the function first_duplicate with a list of numbers and a list of tuples. If your function does not work with both types, then change it until it does work with these two types.

In [29]:
def first_duplicate(lst):
    seen = set()
    for item in lst:
        if item in seen:
            return item
        seen.add(item)
    return None

def input_elements():
    elements = []
    print("Enter elements one by one (press Enter with no input to finish):")
    
    while True:
        user_input = input()
        if user_input == "":
            break
        try:
            # Attempt to evaluate the input (for numbers, tuples)
            element = eval(user_input)
            elements.append(element)
        except:
            # If eval fails, treat it as a string
            elements.append(user_input)
    
    return elements

# Get elements from user
user_elements = input_elements()

# Find the first duplicate
duplicate = first_duplicate(user_elements)
print("First duplicate:", duplicate if duplicate is not None else "None")

Enter elements one by one (press Enter with no input to finish):
(1,2,3)
(2,3,4)
1
2
hello
bird
3
4
shut the door
5
6
pick up sticks
7
8
lay them straight
(2,3,4)
1
2
hello
hello
hello

First duplicate: (2, 3, 4)


## Question 7: statistics (8 marks)
Write a program that asks the user to enter numbers until they enter the character 's' to stop. Store the numbers in a numpy array. Print out the mean and standard deviation of the values entered. Hints: (1) Use a while loop to input values until the letter s is entered. (2) Append the values to a list in the while loop and create a numpy array from the list after all the values have been entered. (3) The method std() returns the standard deviation of a numpy array.

In [32]:
import numpy as np

def collect_numbers():
    numbers = []
    print("Enter numbers one by one. Type 's' to stop.")
    
    while True:
        user_input = input("Enter a number or 's' to stop: ")
        if user_input == 's':
            break
        try:
            number = float(user_input)
            numbers.append(number)
        except ValueError:
            print("Invalid input. Please enter a valid number.")
    
    return np.array(numbers)

# Collect numbers from user
num_array = collect_numbers()

if num_array.size > 0:
    # Calculate mean and standard deviation
    mean = num_array.mean()
    std_dev = num_array.std()
    print(f"Mean: {mean}")
    print(f"Standard Deviation: {std_dev}")
else:
    print("No valid numbers entered.")

Enter numbers one by one. Type 's' to stop.
Enter a number or 's' to stop: 1.1
Enter a number or 's' to stop: 2.2
Enter a number or 's' to stop: 3.3
Enter a number or 's' to stop: 4.4
Enter a number or 's' to stop: 5
Enter a number or 's' to stop: 6.6
Enter a number or 's' to stop: 7.7
Enter a number or 's' to stop: 8.8
Enter a number or 's' to stop: 9.9
Enter a number or 's' to stop: 10
Enter a number or 's' to stop: 20
Enter a number or 's' to stop: s
Mean: 7.181818181818182
Standard Deviation: 4.974812592508235


## Question 8: inner matrix (6 marks)
Write code to create a 5 x 6 matrix of random values between 0 (included) and 1 (excluded), rounded off to one decimal place. Print out the matrix. Use slicing to extract the matrix consisting of the values not on the outside of the matrix (i.e. the 3 x 4 matrix in the centre). Print out the inner matrix.

In [43]:
import numpy as np

# Create a 5x6 matrix of random values scaled to 0 to just under 1
matrix = np.random.rand(5, 6)

# Round the matrix to one decimal place
matrix = np.round(matrix, 1)

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Extract the 3x4 matrix from the center
inner_matrix = matrix[1:4, 1:5]

# Print the inner matrix
print("\nInner Matrix:")
print(inner_matrix)

Original Matrix:
[[0.3 0.7 0.3 0.9 0.4 0. ]
 [0.8 0.5 0.3 0.9 0.1 0.1]
 [0.5 0.5 0.3 0.3 0.2 0.3]
 [0.5 0.2 0.8 0.9 0.1 0.5]
 [0.7 0.2 0.8 0.3 0.3 0.4]]

Inner Matrix:
[[0.5 0.3 0.9 0.1]
 [0.5 0.3 0.3 0.2]
 [0.2 0.8 0.9 0.1]]
